### ISSUE TITLE
MD代码段过长被截断

### ISSUE THREAD

**Issue by ReturnTmp** [xdlrt/mds#41]
如果使用 MD 代码段时出现如下问题，代码超出屏幕，然后粘贴到公众号后超出部分被截断
![image](https://github.com/xdlrt/mds/assets/99105301/af33e5bc-8def-4e78-a5a2-a9b3884c4513)

**Comment by xdlrt** [comment]
抱歉，目前还没有支持代码段的能力，我抽时间加一下

**Comment by ReturnTmp** [comment]
感谢修复！
